/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TradeRouteRouteImport } from './routes/trade/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeIndexRouteImport } from './routes/trade/index'
import { Route as TradeSellRouteImport } from './routes/trade/sell'
import { Route as TradeBuyRouteImport } from './routes/trade/buy'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRouteRoute = TradeRouteRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeIndexRoute = TradeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TradeRouteRoute,
} as any)
const TradeSellRoute = TradeSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => TradeRouteRoute,
} as any)
const TradeBuyRoute = TradeBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => TradeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trade': typeof TradeRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/trade/buy': typeof TradeBuyRoute
  '/trade/sell': typeof TradeSellRoute
  '/trade/': typeof TradeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/trade/buy': typeof TradeBuyRoute
  '/trade/sell': typeof TradeSellRoute
  '/trade': typeof TradeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trade': typeof TradeRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/trade/buy': typeof TradeBuyRoute
  '/trade/sell': typeof TradeSellRoute
  '/trade/': typeof TradeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trade'
    | '/admin'
    | '/history'
    | '/trade/buy'
    | '/trade/sell'
    | '/trade/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/history' | '/trade/buy' | '/trade/sell' | '/trade'
  id:
    | '__root__'
    | '/'
    | '/trade'
    | '/admin'
    | '/history'
    | '/trade/buy'
    | '/trade/sell'
    | '/trade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TradeRouteRoute: typeof TradeRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  HistoryRoute: typeof HistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/': {
      id: '/trade/'
      path: '/'
      fullPath: '/trade/'
      preLoaderRoute: typeof TradeIndexRouteImport
      parentRoute: typeof TradeRouteRoute
    }
    '/trade/sell': {
      id: '/trade/sell'
      path: '/sell'
      fullPath: '/trade/sell'
      preLoaderRoute: typeof TradeSellRouteImport
      parentRoute: typeof TradeRouteRoute
    }
    '/trade/buy': {
      id: '/trade/buy'
      path: '/buy'
      fullPath: '/trade/buy'
      preLoaderRoute: typeof TradeBuyRouteImport
      parentRoute: typeof TradeRouteRoute
    }
  }
}

interface TradeRouteRouteChildren {
  TradeBuyRoute: typeof TradeBuyRoute
  TradeSellRoute: typeof TradeSellRoute
  TradeIndexRoute: typeof TradeIndexRoute
}

const TradeRouteRouteChildren: TradeRouteRouteChildren = {
  TradeBuyRoute: TradeBuyRoute,
  TradeSellRoute: TradeSellRoute,
  TradeIndexRoute: TradeIndexRoute,
}

const TradeRouteRouteWithChildren = TradeRouteRoute._addFileChildren(
  TradeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TradeRouteRoute: TradeRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  HistoryRoute: HistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
